#!/bin/bash

set -e
set -o pipefail

READLINK=$(type -p greadlink readlink | head -1 || true)
if [ -z "$READLINK" ]; then
  echo "rbenv: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

PROJECT_ROOT="$(abs_dirname "$0")/.."

cd "$PROJECT_ROOT"

exec bundle exec bin/denonandon "$@" | logger -t denonandon 2>&1